runtime: python310

env_variables:
  DOMAIN_NAME: "psyclonicstudios.com.au"
handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/img/psyclonic-simple-favicon.png
  upload: static/img/psyclonic-simple-favicon.png
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto