runtime: python37

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/img/psyclonic-simple-favicon.png
  upload: static/img/psyclonic-simple-favicon.png
- url: /.*
  script: auto